/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// Toggle LED When button is pressed

#include <stdint.h>


#include "stm32f407xx_GPIO_driver.h"


int main(void)
{
	//enable clk port D & A
	GPIO_PeriClkControl(GPIOA,ENABLE);
	GPIO_PeriClkControl(GPIOD,ENABLE);

	//PORT D PIN 12 CONFIG
	GPIO_Handle_t my_GPIOD;
	my_GPIOD.pGPIOx = GPIOD;

	my_GPIOD.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	my_GPIOD.GPIO_PinConfig.GPIO_PinNum = 12;
	my_GPIOD.GPIO_PinConfig.GPIO_PinOPType = OUT_PP;


	//PORT A PIN 0 CONFIG AS INPUT FROM BUTTOM
	GPIO_Handle_t my_GPIOA;
	my_GPIOA.pGPIOx = GPIOA;

	my_GPIOA.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
	my_GPIOA.GPIO_PinConfig.GPIO_PinNum = 0;

	//Init PD12 AND PA0
	GPIO_Init(&my_GPIOA);
	GPIO_Init(&my_GPIOD);

	//TOGGLE LED PORTD PIN 12

	while(1){
		while(GPIO_ReadFromInputPin(GPIOA,0)){
			GPIO_ToggleOutputPin(GPIOD, 12);
			for(uint32_t i=0 ; i < 300000 ; i++ );
		}
		GPIO_WriteToOutputPin(GPIOD,12,RESET);
	}

	return 0;
}
